#check java needed?

#installation by package
- name: Installation prerequisites
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - "java-{{ jdk_version }}-openjdk"
    - "java-{{ jdk_version }}-openjdk-devel"
  notify:
    - save java details
  become: yes
  no_log: True

- name: JAVA_HOME and PATH
  shell: |-
    cd  /usr/lib/jvm/java-1.8.0-openjdk*
    echo "export JAVA_HOME=${PWD}/jre/bin" >> ~/.bashrc
    echo "export PATH=${PATH}:${JAVA_HOME}" >> ~/.bashrc
    source ~/.bashrc 

- name: Get info about java
  shell: |-
    java -version 2>&1 | awk '/version/{print $3}'
  register: java_version
  notify:
    - save java details
