apiVersion: v1
kind: Secret
metadata:
  name: special-secret-v3
stringData:
  PASSWORD: very-strong-passwd
  USERNAME: very-big-admin
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
spec:
  containers:
  - name: container
    image: busybox
    command: [ "/bin/sh", "-c", "ls -l /etc/secrets/" ]
    volumeMounts:
    - name: secrets-vol
      mountPath: /etc/secrets
  volumes:
  - name: secrets-vol
    secret:
      secretName: special-secret-v3
  restartPolicy: Never